AWSTemplateFormatVersion: 2010-09-09

Description: |
  CloudFormation Template for Phonebook Application.
  Phonebook is deployed ALB, Auto-scaling Group with RDS.

ParameterName:
  KeyPairName:
    Description: Enter the name of your Key Pair for SSH connections.
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must one of the existing EC2 KeyPair
Resources:
  ALBSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable HTTP for App Load Balancer
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  WebServerSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable HTTP, SSH for Flask Web Server
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !GetAtt ALBSecurityGroup.GroupID
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  WebServerLT:
      Type: AWS::EC2::LaunchTemplate
      Properties: 
        LaunchTemplateData:
          ImageId: ami-0947d2ba12ee1ff75
          InstanceType: t2.micro
          KeyName: !Ref KeyPairName
          SecurityGroupIds: 
            - !GetAtt WebServerSecurityGroup.GroupId
          TagSpecifications: 
            - ResourceType: instance
              Tags: 
                - Key: Name
                  Value: !Sub Web Server of ${AWS::StackName} Stack 
          UserData:
            Fn::Base64: 
              !Sub
                - |
                  #! /bin/bash
                  yum update -y
                  yum install python3 -y
                  pip3 install flask
                  pip3 install flask_mysql
                  echo "${MyDBURI}" > /home/ec2-user/dbserver.endpoint
                  FOLDER="https://raw.githubusercontent.com/baurkika/DevOpsProjects/master/Project6-phonebook-web-application/"
                  curl -s --create-dirs -o "/home/ec2-user/templates/index.html" -L "$FOLDER"templates/index.html
                  curl -s --create-dirs -o "/home/ec2-user/templates/add-update.html" -L "$FOLDER"templates/add-update.html
                  curl -s --create-dirs -o "/home/ec2-user/templates/delete.html" -L "$FOLDER"templates/delete.html
                  curl -s --create-dirs -o "/home/ec2-user/app.py" -L "$FOLDER"phonebook-app.py
                  python3 /home/ec2-user/app.py
                - MyDBURI: !GetAtt MyDatabaseServer.Endpoint.Addres
  WebServerTG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      Port: 80
      Protocol: HTTP
      TargetType: instance
      VpcId: !GetAtt WebServerSecurityGroup.VpcId
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Scheme: internet-facing
      SecurityGroups: 
        - !GetAtt ALBSecurityGroup.GroupId
      Subnets:
        - subnet-9dbde8b3
        - subnet-c5551e99
        - subnet-10581677
        - subnet-3106063e
        - subnet-4bfce201
        - subnet-ed30a2d3
      Type: application
  ALBListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions: #required
        - TargetGroupArn: !Ref WebServerTG
          Type: forward
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
  WebServerASG:
      Type: AWS::AutoScaling::AutoScalingGroup
      Properties: 
        AvailabilityZones: 
          !GetAZs ""
        DesiredCapacity: 2
        HealthCheckGracePeriod: 300
        HealthCheckType: ELB
        LaunchTemplate: 
          LaunchTemplateId: !Ref WebServerLT
          Version: !GetAtt WebServerLT.LatestVersionNumber 
        MaxSize: 3
        MinSize: 1
        TargetGroupARNs: 
          - !Ref WebServerTG
  MyDBSecurityGroup:
    Type: "AWS::RDS::DBSecurityGroup"
    Properties:
      GroupDescription: Frontend Access
      DBSecurityGroupIngress:
        - CIDRIP: 0.0.0.0/0
        - EC2SecurityGroupId: !GetAtt WebServerSecurityGroup.GroupId
  MyDatabaseServer:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: 20
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      BackupRetentionPeriod: 0
      DBInstanceClass: db.t2.micro #required
      DBInstanceIdentifier: phonebook-app-db
      DBName: phonebook
      Engine: MySQL
      EngineVersion: 8.0.19
      MasterUserPassword: Baurjan_1
      MasterUsername: admin
      MonitoringInterval: 0
      MultiAZ: false
      Port: 3306
      PubliclyAccessible: true
      DBSecurityGroups:
        - Ref: MyDBSecurityGroup

Outputs:
  WebsiteURL:
    Value: !Sub 
      - http://${ALBAddress}
      - ALBAddress: !GetAtt ApplicationLoadBalancer.DNSName
    Description: Phonebook Application Load Balancer URL